FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04
############################## SYSTEM PARAMETERS ##############################
# * Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID="${UID}"
ARG SHELL=/bin/bash
ARG HARDWARE=x86_64
ARG ENTRYPOINT_FILE=entrypint.sh

# * Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
# ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# * Setup users and groups
RUN groupadd --gid "${GID}" "${GROUP}" && \
    useradd --gid "${GID}" --uid "${UID}" -ms "${SHELL}" "${USER}" && \
    mkdir -p /etc/sudoers.d && \
    echo "${USER}:x:${UID}:${UID}:${USER},,,:/home/${USER}:${shell}" >> /etc/passwd && \
    echo "${USER}:x:${UID}:" >> /etc/group && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" && \
    chmod 0440 "/etc/sudoers.d/${USER}"

# * Replace apt urls
# ? Change to tku
RUN sed -i 's@archive.ubuntu.com@ftp.tku.edu.tw@g' /etc/apt/sources.list
# ? Change to Taiwan
# RUN sed -i 's@archive.ubuntu.com@tw.archive.ubuntu.com@g' /etc/apt/sources.list

# * Time zone
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/"${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

############################### INSTALL #######################################
# * Install packages
RUN apt update && \
    apt install -y --no-install-recommends \
        sudo \
        git \
        htop \
        wget \
        curl \
        psmisc \
        lsb-release \
        # * Shell
        tmux \
        terminator \
        # * base tools
        vim \
        pkg-config \
        build-essential \
        python3-pip \
        python3-dev \
        python3-setuptools \
        libopencv-dev \
        # pytorch-YOLOv4
        libfreetype6-dev \
        # usb_cam
        libv4l-dev \
        v4l-utils \
        # * Work tools
    && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# * Install pytorch-YOLOv4
RUN git clone https://github.com/Tianxiaomo/pytorch-YOLOv4 /home/"${USER}"/pytorch-YOLOv4 && \
    chown -R "${USER}":"${GROUP}" /home/"${USER}"/pytorch-YOLOv4

# * Install ROS desktop full
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > \
    /etc/apt/sources.list.d/ros-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - && \
    apt update && \
    apt install -y --no-install-recommends \
        ros-noetic-desktop-full \
        ros-noetic-rosserial-python \
        ros-noetic-turtlebot3-msgs \
        ros-noetic-gmapping \
        ros-noetic-hls-lfcd-lds-driver \
        python3-catkin-tools \
        && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# ROS config
ENV ROS_MASTER_URL=http://localhost:11311
ENV ROS_HOSTNAME=localhost
ENV ROS_IP=localhost

# turtlebot3 config
ENV TURTLEBOT3_MODEL=burger
ENV LDS_MODEL=LDS-01
ENV OPENCR_PORT=/dev/opencr
ENV OPENCR_MODEL=burger_noetic

############################### OTHER #######################################
# * Copy entrypoint
# ? Requires docker version >= 17.09
COPY --chmod=0775 ./${ENTRYPOINT_FILE} /entrypoint.sh
# ? docker version < 17.09
# COPY ./${ENTRYPOINT_FILE} /entrypoint.sh
# RUN sudo chmod 0775 /entrypoint.sh

# * Copy custom configuration
# ? Requires docker version >= 17.09
COPY --chown="${USER}":"${GROUP}" --chmod=0775 config config
# ? docker version < 17.09
# COPY config config
# RUN sudo chown -R "${USER}":"${GROUP}" config \
    # && sudo chmod -R 0775 config

# * Install python packages
RUN ./config/pip/pip_setup.sh

# * Make SSH available
EXPOSE 22

############################## USER CONFIG ####################################
# * Switch user to ${USER}
USER ${USER}

# * Setup user configuration
RUN ./config/shell/bash_setup.sh "${USER}" "${GROUP}" && \
    ./config/shell/terminator/terminator_setup.sh "${USER}" "${GROUP}" && \
    ./config/shell/tmux/tmux_setup.sh "${USER}" "${GROUP}" && \
    sudo rm -rf /config


# * Switch workspace to /home/"${USER}"/work
RUN sudo mkdir /home/"${USER}"/work
WORKDIR /home/"${USER}"/work

# ENTRYPOINT [ "/entrypoint.sh", "terminator" ]
# ENTRYPOINT "/entrypoint.sh", "tmux" ]
ENTRYPOINT [ "/entrypoint.sh", "bash" ]
# ENTRYPOINT [ "/entrypoint.sh" ]
